name: Hello world pipeline

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: "Deploy site to netlify"
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
